-- Seed exercises the trainer can reference by name. Program generation maps
-- Claude's exercise names onto these case-insensitively; anything unmatched
-- gets inserted on the fly with custom = true (see api/_progression.js /
-- trainer.js), so this list only needs to be a solid common core.
insert into exercises (name, category, equipment, is_bodyweight) values
  ('Bench Press', 'chest', 'barbell', false),
  ('Incline Bench Press', 'chest', 'barbell', false),
  ('Dumbbell Bench Press', 'chest', 'dumbbells', false),
  ('Incline Dumbbell Press', 'chest', 'dumbbells', false),
  ('Push-up', 'chest', 'bodyweight', true),
  ('Dumbbell Fly', 'chest', 'dumbbells', false),
  ('Cable Fly', 'chest', 'cable', false),
  ('Dip', 'chest', 'bodyweight', true),

  ('Overhead Press', 'shoulders', 'barbell', false),
  ('Dumbbell Shoulder Press', 'shoulders', 'dumbbells', false),
  ('Arnold Press', 'shoulders', 'dumbbells', false),
  ('Lateral Raise', 'shoulders', 'dumbbells', false),
  ('Front Raise', 'shoulders', 'dumbbells', false),
  ('Face Pull', 'shoulders', 'cable', false),
  ('Rear Delt Fly', 'shoulders', 'dumbbells', false),

  ('Deadlift', 'back', 'barbell', false),
  ('Romanian Deadlift', 'back', 'barbell', false),
  ('Barbell Row', 'back', 'barbell', false),
  ('Dumbbell Row', 'back', 'dumbbells', false),
  ('Pull-up', 'back', 'bodyweight', true),
  ('Chin-up', 'back', 'bodyweight', true),
  ('Lat Pulldown', 'back', 'cable', false),
  ('Seated Cable Row', 'back', 'cable', false),
  ('Cable Pulldown', 'back', 'cable', false),

  ('Squat', 'legs', 'barbell', false),
  ('Front Squat', 'legs', 'barbell', false),
  ('Goblet Squat', 'legs', 'dumbbells', false),
  ('Split Squat', 'legs', 'dumbbells', false),
  ('Bulgarian Split Squat', 'legs', 'dumbbells', false),
  ('Leg Press', 'legs', 'machine', false),
  ('Leg Extension', 'legs', 'machine', false),
  ('Leg Curl', 'legs', 'machine', false),
  ('Walking Lunge', 'legs', 'dumbbells', false),
  ('Step-up', 'legs', 'dumbbells', false),
  ('Calf Raise', 'legs', 'machine', false),
  ('Standing Calf Raise', 'legs', 'dumbbells', false),
  ('Hip Thrust', 'legs', 'barbell', false),
  ('Glute Bridge', 'legs', 'bodyweight', true),

  ('Barbell Curl', 'arms', 'barbell', false),
  ('Dumbbell Curl', 'arms', 'dumbbells', false),
  ('Hammer Curl', 'arms', 'dumbbells', false),
  ('Preacher Curl', 'arms', 'barbell', false),
  ('Triceps Pushdown', 'arms', 'cable', false),
  ('Overhead Triceps Extension', 'arms', 'dumbbells', false),
  ('Skull Crusher', 'arms', 'barbell', false),
  ('Close-Grip Bench Press', 'arms', 'barbell', false),

  ('Plank', 'core', 'bodyweight', true),
  ('Side Plank', 'core', 'bodyweight', true),
  ('Hollow Hold', 'core', 'bodyweight', true),
  ('Dead Bug', 'core', 'bodyweight', true),
  ('Hanging Leg Raise', 'core', 'bodyweight', true),
  ('Cable Crunch', 'core', 'cable', false),
  ('Russian Twist', 'core', 'bodyweight', true),
  ('Ab Wheel Rollout', 'core', 'bodyweight', true),

  ('Kettlebell Swing', 'full_body', 'kettlebell', false),
  ('Kettlebell Goblet Squat', 'full_body', 'kettlebell', false),
  ('Burpee', 'full_body', 'bodyweight', true),
  ('Farmer''s Carry', 'full_body', 'dumbbells', false),
  ('Clean and Press', 'full_body', 'barbell', false),
  ('Thruster', 'full_body', 'dumbbells', false),
  ('Mountain Climber', 'full_body', 'bodyweight', true),
  ('Jump Rope', 'cardio', 'bodyweight', true),
  ('Rowing Machine', 'cardio', 'machine', false)
on conflict (name) do nothing;
